armadillo: true

left_finger_topic_pub: 'left_finger_controller/command'
left_finger_topic_sub: 'left_finger_controller/state'
left_finger_joint: 'left_finger_joint'

right_finger_topic_pub: 'right_finger_controller/command'
right_finger_topic_sub: 'right_finger_controller/state'
right_finger_joint: 'right_finger_joint'

pan_topic_pub: 'pan_controller/command'
pan_topic_sub: 'pan_controller/state'
pan_joint: 'head_pan_joint'

tilt_topic_pub: 'tilt_controller/command'
tilt_topic_sub: 'tilt_controller/state'
tilt_joint: 'head_tilt_joint'
                               
# RiCBoard                                
battery_pin: 17
battery_voltage_divider_ratio: 11.0
battery_max: 29.3
battery_min: 24.0

imu_fusion_hz: 50
imu_enable_gyro: true
imu_enable_fuse_compass: true
imu_frame_id: 'base_link'
imu_linear_acc_fix: [0, 1, 0,
                     -1, 0, 0,
                     0, 0, -1]

imu_angular_velocity_fix: [0, -1, 0,
                           1, 0, 0,
                           0, 0, 1]

imu_magnetometer_fix: [1, 0, 0,
                       0, 1, 0,
                       0, 0, 1]

imu_rotation_fix: [0, 1, 0,
                   1, 0, 0,
                   0, 0, -1]
 
ultrasonic_size: 3

ultrasonic0_pin: 14
ultrasonic0_frame_id: 'left_urf_link'
ultrasonic0_topic_name: 'URF/left'
ultrasonic0_sonar_name:  'Max_Sonar_LV'

ultrasonic1_pin: 15
ultrasonic1_frame_id: 'right_urf_link'
ultrasonic1_topic_name: 'URF/right'
ultrasonic1_sonar_name:  'Max_Sonar_LV'

ultrasonic2_pin: 16
ultrasonic2_frame_id: 'rear_urf_link'
ultrasonic2_topic_name: 'URF/rear'
ultrasonic2_sonar_name:  'Max_Sonar_LV'


close_motor_size: 2

motor0_motor_type: 0
motor0_encoder_pin_A: 27
motor0_encoder_pin_B: 28
motor0_lpf_hz_speed: 80
motor0_lpf_hz_input: 1000
motor0_lpf_alpha_speed: 0.27
motor0_lpf_alpha_input: 1.0
motor0_pid_hz: 1000
motor0_ppr: 1675
motor0_timeout: 0
motor0_motor_direction: 1
motor0_encoder_direction: -1
motor0_kp: 85.0
motor0_ki: 55.0
motor0_kd: 0.0
motor0_kff: 40.0
motor0_max_set_point_speed: 9.0
motor0_min_set_point_speed: -9.0
motor0_max_set_point_position: 0.0
motor0_min_set_point_position: 0.0
motor0_limit: 0.2
motor0_stop_limit_max: 15.0
motor0_stop_limit_min: -15.0
motor0_motor_address: 0
motor0_motor_emergency_pin: 12
motor0_motor_emergency_pin_type: 1
motor0_joint: ['left_wheel_joint']
motor0_mode: 0
motor0_bais_min: -1
motor0_bais_max: 1


motor1_motor_type: 0

motor1_encoder_pin_A: 29
motor1_encoder_pin_B: 30
motor1_encoder_direction: 1
motor1_lpf_hz_speed: 80
motor1_lpf_hz_input: 1000
motor1_lpf_alpha_speed: 0.27
motor1_lpf_alpha_input: 1.0
motor1_pid_hz: 1000
motor1_ppr: 1675
motor1_timeout: 0
motor1_motor_direction: -1
motor1_kp: 85.0
motor1_ki: 55.0
motor1_kd: 0.0
motor1_kff: 40.0
motor1_max_set_point_speed: 9.0
motor1_min_set_point_speed: -9.0
motor1_max_set_point_position: 0.0
motor1_min_set_point_position: 0.0
motor1_limit: 0.2
motor1_stop_limit_max: 15.0
motor1_stop_limit_min: -15.0
motor1_motor_address: 1
motor1_motor_emergency_pin: 12
motor1_motor_emergency_pin_type: 1
motor1_joint: ['right_wheel_joint']
motor1_mode: 0
motor1_bais_min: -1
motor1_bais_max: 1

position_motor_size: 1 
positionMotor0_motor_type: 1
positionMotor0_a: 0.00064833
positionMotor0_b: -0.026
positionMotor0_lpf_hz_speed: 63
positionMotor0_lpf_hz_input: 50
positionMotor0_pid_hz: 1000
positionMotor0_ppr: 2503
positionMotor0_timeout: 0
positionMotor0_motor_direction: -1
positionMotor0_encoder_direction: 1
positionMotor0_lpf_alpha_speed: 0.21
positionMotor0_lpf_alpha_input: 0.05
positionMotor0_kp: 3000.0
positionMotor0_ki: 250.0
positionMotor0_kd: 0.0
positionMotor0_kff: 0.0
positionMotor0_k: -30.0 # Exp!!
positionMotor0_max_set_point_speed: 0.06
positionMotor0_min_set_point_speed: -0.06
positionMotor0_max_set_point_position: 0.37
positionMotor0_min_set_point_position: 0.08
positionMotor0_limit: 0.3
positionMotor0_motor_address: 20
positionMotor0_motor_emergency_pin: 12
positionMotor0_motor_emergency_pin_type: 1
positionMotor0_joint: 'torso_joint'
positionMotor0_mode: 1
positionMotor0_read_pin: 21
positionMotor0_tolerance: 0.01
positionMotor0_tolerance_time: 1000 # millis
positionMotor0_stop_limit_max: 0.38
positionMotor0_stop_limit_min: 0.04

gps_baudrate: 9600
gps_topic_name: 'gps'
gps_frame_id: 'base_link'

#RiCBoard




