controller_list:
    - name: arm_trajectory_controller
      default: true
      type: FollowJointTrajectory
      action_ns: follow_joint_trajectory
      joints: 
        - rotation1_joint
        - shoulder1_joint
        - shoulder2_joint
        - rotation2_joint
        - shoulder3_joint
        - wrist_joint

    - name: gripper_controller
      default: true
      type: GripperCommand
      action_ns: gripper_cmd

      joints: 
        - left_finger_joint
        - right_finger_joint
